---

- name: Install git.
  apt:
    name: git
    state: present
    update_cache: yes
  become: yes

- name: Ensure the Directory to hold the Private Key Exists.
  file:
    path: "{{ deploy_key_dir }}"
    state: directory

- name: Copy Deploy Token Private Key to Host.
  template:
    src: id_rsa.j2
    dest: "{{ deploy_key_dir }}/id_rsa"
    mode: "0600"

- name: Ensure the Directory to hold the Project Exists.
  file:
    path: "{{ project_dir }}"
    state: directory
    mode: '0777'
  become: yes

- name: Clone the repo.
  git:
    repo: "{{ git_repo_url }}"
    dest: "{{ git_repo_dest }}"
    update: yes
    accept_hostkey: yes
  become: yes
